version: "3.8"

services:
  Execution:
  image: nethermind/nethermind
  container_name: execution
  restart: unless-stoped
  ports:
    - "8545:8545"
    - "8551:8551"
  
  volumes:
    - ./data/nethermind:/nethermind/data
    - ./jwtsecret:/engine.jwt
  
  command: >
    -c sepolia
    --JsonRpc.Enabled=true
    --JsonRpc.Host=0.0.0.0
    --JsonRpc.port=8545
    --JsonRpc.EngineHost=0.0.0.0
    --JsonRpc.EnginePort=8551
    --JsonRpc.JwtSecretFile=/engine.jwt
  
  consensus:
    image: sigp/lighthouse:latest
    container_name: beacon
    restart: unless-stoped
    depends_on:
      - execution
    ports:
      - 5052:5052
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./jwtsecret:/engine.jwt
    command: >
      lighthouse bn
      --network sepolia
      --http
      --execution-endpoint http://execution:8551
      --jwt-secrets /engine.jwt
      --checkpoint-sync-url https://sepolia.beaconstate.info